# Generated by Django 3.2.10 on 2022-01-02 17:48

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('fetcher', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('removed', models.DateTimeField(blank=True, null=True, verbose_name='Remove Time')),
                ('title', models.CharField(max_length=20)),
                ('description', models.TextField()),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FollowedRSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Creation time')),
            ],
        ),
        migrations.CreateModel(
            name='UserFeedBookmarkItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fetcher.feeditem')),
            ],
        ),
    ]
