parsed_data = {'bozo': False, 'entries': [
    {'title': 'انواع محبوب ترین گل های آپارتمانی و روش نگهداری آن ها',
     'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                      'value': 'انواع محبوب ترین گل های آپارتمانی و روش نگهداری آن ها'}, 'links': [
        {'rel': 'alternate', 'type': 'text/html',
         'href': 'https://www.tahghighestan.ir/the-most-popular-apartment-flowers/'}],
     'link': 'https://www.tahghighestan.ir/the-most-popular-apartment-flowers/',
     'comments': 'https://www.tahghighestan.ir/the-most-popular-apartment-flowers/#respond',
     'authors': [{'name': 'حسین شریفی'}], 'author': 'حسین شریفی', 'author_detail': {'name': 'حسین شریفی'},
     'published': 'Mon, 27 Dec 2021 10:17:26 +0000',
     'tags': [{'term': 'عمومی', 'scheme': None, 'label': None},
              {'term': 'انواع محبوب ترین گل های آپارتمانی و روش نگهداری آن ها', 'scheme': None, 'label': None},
              {'term': 'خرید اینترنتی محبوب ترین گل های آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'خرید اینترنتی گل آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'خرید اینترنتی گل های آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'روش نگهداری گل های اپارتمانی', 'scheme': None, 'label': None},
              {'term': 'محبوب ترین گل های آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'ویژگی گل های آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'گل آپارتمانی', 'scheme': None, 'label': None},
              {'term': 'گل ها برای رشد صحیح به چه مواردی نیازمند هستند؟', 'scheme': None, 'label': None}],
     'id': 'https://www.tahghighestan.ir/?p=38824', 'guidislink': False,
     'summary': 'انواع محبوب ترین گل های آپارتمانی و روش نگهداری آن ها محبوب ترین گل های آپارتمانی به عنوان پرفروش ترین نمونه های موجود در گل فروشی ها شناخته می شوند. این نمونه ها نیازمند نگهداری صحیح، روش های جدید در این زمینه و &#8230; هستند. برای آن که بتوانید بهترین نمونه های موجود را در [&#8230;]',
     'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                        'value': 'انواع محبوب ترین گل های آپارتمانی و روش نگهداری آن ها محبوب ترین گل های آپارتمانی به عنوان پرفروش ترین نمونه های موجود در گل فروشی ها شناخته می شوند. این نمونه ها نیازمند نگهداری صحیح، روش های جدید در این زمینه و &#8230; هستند. برای آن که بتوانید بهترین نمونه های موجود را در [&#8230;]'},
     'wfw_commentrss': 'https://www.tahghighestan.ir/the-most-popular-apartment-flowers/feed/',
     'slash_comments': '0'}, {
                              'title_detail': {'type': 'text/plain', 'language': None,
                                               'base': 'https://www.tahghighestan.ir/feed/',
                                               'value': 'هر آنچه که باید از هزینه و قیمت تدریس خصوصی در ایران بدانید!'},
                              'links': [{'rel': 'alternate', 'type': 'text/html',
                                         'href': 'https://www.tahghighestan.ir/cost-and-price-of-tutoring-in-iran/'}],
                              'link': 'https://www.tahghighestan.ir/cost-and-price-of-tutoring-in-iran/',
                              'comments': 'https://www.tahghighestan.ir/cost-and-price-of-tutoring-in-iran/#respond',
                              'authors': [{'name': 'حسین شریفی'}], 'author': 'حسین شریفی',
                              'author_detail': {'name': 'حسین شریفی'},
                              'published': 'Sun, 19 Dec 2021 08:46:36 +0000',
                              'tags': [{'term': 'عمومی', 'scheme': None, 'label': None},
                                       {'term': 'استادبانک', 'scheme': None, 'label': None},
                                       {'term': 'انتخاب بهترین معلم خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'تدریس خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'تدریس خصوصی در ایران', 'scheme': None, 'label': None},
                                       {'term': 'تعرفه تدریس خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'تعرفه تدریس خصوصی در ایران', 'scheme': None, 'label': None},
                                       {'term': 'تفاوت قیمت کلاس خصوصی در منزل و آنلاین', 'scheme': None,
                                        'label': None},
                                       {'term': 'قیمت تدریس خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'قیمت تدریس خصوصی در ایران', 'scheme': None, 'label': None},
                                       {'term': 'قیمت تدریس خصوصی ریاضی', 'scheme': None, 'label': None},
                                       {'term': 'قیمت تدریس خصوصی زبان', 'scheme': None, 'label': None},
                                       {'term': 'قیمت معلم خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'هزینه تدریس خصوصی', 'scheme': None, 'label': None},
                                       {'term': 'هزینه تدریس خصوصی در ایران', 'scheme': None, 'label': None},
                                       {'term': 'هزینه معلم خصوصی ابتدایی', 'scheme': None, 'label': None},
                                       {'term': 'هزینه و قیمت تدریس خصوصی در ایران', 'scheme': None,
                                        'label': None}], 'id': 'https://www.tahghighestan.ir/?p=38756',
                              'guidislink': False,
                              'summary': 'هر آنچه که باید از هزینه و قیمت تدریس خصوصی در ایران بدانید! هزینه تدریس خصوصی، یکی از ملاک\u200cهای اصلی والدین و دانش\u200cآموزان در هنگام انتخاب معلم خصوصی است. مخارج تحصیلات دانش\u200cآموز، جنبه\u200cهای مختلف و متعددی دارد که خانواده را مجبور به برنامه\u200cریزی دقیق و حساب\u200cشده می\u200cکند. میان همه\u200cی نیازهای آموزشی محصل، شرکت در کلاس [&#8230;]',
                              'summary_detail': {'type': 'text/html', 'language': None,
                                                 'base': 'https://www.tahghighestan.ir/feed/',
                                                 'value': 'هر آنچه که باید از هزینه و قیمت تدریس خصوصی در ایران بدانید! هزینه تدریس خصوصی، یکی از ملاک\u200cهای اصلی والدین و دانش\u200cآموزان در هنگام انتخاب معلم خصوصی است. مخارج تحصیلات دانش\u200cآموز، جنبه\u200cهای مختلف و متعددی دارد که خانواده را مجبور به برنامه\u200cریزی دقیق و حساب\u200cشده می\u200cکند. میان همه\u200cی نیازهای آموزشی محصل، شرکت در کلاس [&#8230;]'},
                              'wfw_commentrss': 'https://www.tahghighestan.ir/cost-and-price-of-tutoring-in-iran/feed/',
                              'slash_comments': '0'},
    {'title': 'بهترین رشته\u200cها برای مهاجرت به استرالیا کدام هستند؟',
     'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                      'value': 'بهترین رشته\u200cها برای مهاجرت به استرالیا کدام هستند؟'}, 'links': [
        {'rel': 'alternate', 'type': 'text/html',
         'href': 'https://www.tahghighestan.ir/what-are-the-best-courses-to-immigrate-to-australia/'}],
     'link': 'https://www.tahghighestan.ir/what-are-the-best-courses-to-immigrate-to-australia/',
     'comments': 'https://www.tahghighestan.ir/what-are-the-best-courses-to-immigrate-to-australia/#respond',
     'authors': [{'name': 'fatemeh.farhad'}], 'author': 'fatemeh.farhad',
     'author_detail': {'name': 'fatemeh.farhad'}, 'published': 'Sun, 28 Nov 2021 13:16:57 +0000',
     'tags': [{'term': 'عمومی', 'scheme': None, 'label': None},
              {'term': 'برترین رشته\u200cها برای مهاجرت به استرالیا', 'scheme': None, 'label': None},
              {'term': 'بهترین رشته\u200cها برای مهاجرت به استرالیا', 'scheme': None, 'label': None},
              {'term': 'رشته\u200cهای تحصیلی برای مهاجرت به استرالیا', 'scheme': None, 'label': None},
              {'term': 'مهاجرت به استرالیا', 'scheme': None, 'label': None}],
     'id': 'https://www.tahghighestan.ir/?p=38594', 'guidislink': False,
     'summary': 'بهترین رشته\u200cها برای مهاجرت به استرالیا کدام هستند؟ استرالیا؛ کشوری در نیم کره جنوبی در میان اقیانوس هند و آرام که از نظر جمعیت پنجاه و پنجمین کشور جهان می\u200cباشد.استرالیا جزء یکی از مهاجرپذیرترین کشورهای جهان محسوب می\u200cشود، اقتصاد کشور استرالیا نیز بر همین اساس پایه\u200cریزی شده است. از نظر علمی نیز کشور استرالیا، دارای [&#8230;]',
     'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                        'value': 'بهترین رشته\u200cها برای مهاجرت به استرالیا کدام هستند؟ استرالیا؛ کشوری در نیم کره جنوبی در میان اقیانوس هند و آرام که از نظر جمعیت پنجاه و پنجمین کشور جهان می\u200cباشد.استرالیا جزء یکی از مهاجرپذیرترین کشورهای جهان محسوب می\u200cشود، اقتصاد کشور استرالیا نیز بر همین اساس پایه\u200cریزی شده است. از نظر علمی نیز کشور استرالیا، دارای [&#8230;]'},
     'wfw_commentrss': 'https://www.tahghighestan.ir/what-are-the-best-courses-to-immigrate-to-australia/feed/',
     'slash_comments': '0'}, {'title': 'علت بوی بد یخچال',
                              'title_detail': {'type': 'text/plain', 'language': None,
                                               'base': 'https://www.tahghighestan.ir/feed/',
                                               'value': 'علت بوی بد یخچال'}, 'links': [
            {'rel': 'alternate', 'type': 'text/html',
             'href': 'https://www.tahghighestan.ir/cause-the-bad-smell-of-the-refrigerator/'}],
                              'link': 'https://www.tahghighestan.ir/cause-the-bad-smell-of-the-refrigerator/',
                              'comments': 'https://www.tahghighestan.ir/cause-the-bad-smell-of-the-refrigerator/#respond',
                              'authors': [{'name': 'حسین شریفی'}], 'author': 'حسین شریفی',
                              'author_detail': {'name': 'حسین شریفی'},
                              'published': 'Sun, 12 Sep 2021 09:23:47 +0000',
                              'tags': [{'term': 'عمومی', 'scheme': None, 'label': None},
                                       {'term': 'اولین علت بوی بد یخچال', 'scheme': None, 'label': None},
                                       {'term': 'دلایل بوی بد یخچال', 'scheme': None, 'label': None},
                                       {'term': 'روش های جلوگیری از بوی بد یخچال', 'scheme': None,
                                        'label': None},
                                       {'term': 'علت بوی بد یخچال', 'scheme': None, 'label': None}],
                              'id': 'https://www.tahghighestan.ir/?p=37846', 'guidislink': False,
                              'summary': 'علت بوی بد یخچال یخچال یکی از وسایل پرکابرد آشپزخانه ها می باشد که مدت زیادی از اختراع آن می گذرد. یخچال ها همه روزه در حال پیشرفت هستند و هر روز مدل جدیدی از یخچال وارد بازار می شود که اشکالات مدل قبلی را رفع کرده و همچنین امکانات جدیدتری نیز به آن اضافه [&#8230;]',
                              'summary_detail': {'type': 'text/html', 'language': None,
                                                 'base': 'https://www.tahghighestan.ir/feed/',
                                                 'value': 'علت بوی بد یخچال یخچال یکی از وسایل پرکابرد آشپزخانه ها می باشد که مدت زیادی از اختراع آن می گذرد. یخچال ها همه روزه در حال پیشرفت هستند و هر روز مدل جدیدی از یخچال وارد بازار می شود که اشکالات مدل قبلی را رفع کرده و همچنین امکانات جدیدتری نیز به آن اضافه [&#8230;]'},
                              'wfw_commentrss': 'https://www.tahghighestan.ir/cause-the-bad-smell-of-the-refrigerator/feed/',
                              'slash_comments': '0'}, {'title': 'کتاب زیست شناسی نشر الگو',
                                                       'title_detail': {'type': 'text/plain', 'language': None,
                                                                        'base': 'https://www.tahghighestan.ir/feed/',
                                                                        'value': 'کتاب زیست شناسی نشر الگو'},
                                                       'links': [{'rel': 'alternate', 'type': 'text/html',
                                                                  'href': 'https://www.tahghighestan.ir/biology-book-publishing-template/'}],
                                                       'link': 'https://www.tahghighestan.ir/biology-book-publishing-template/',
                                                       'comments': 'https://www.tahghighestan.ir/biology-book-publishing-template/#respond',
                                                       'authors': [{'name': 'حسین شریفی'}],
                                                       'author': 'حسین شریفی',
                                                       'author_detail': {'name': 'حسین شریفی'},
                                                       'published': 'Tue, 17 Aug 2021 11:44:51 +0000',
                                                       'tags': [{'term': 'متوسطه دوم', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'پایه دهم', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'پایه دوازدهم', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'پایه یازدهم', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'کمک آموزشی', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'تهیه کتاب های زیست نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'خرید زیست شناسی نشر الگو پایه دهم',
                                                                 'scheme': None, 'label': None}, {
                                                                    'term': 'خرید زیست شناسی نشر الگو پایه دوازدهم',
                                                                    'scheme': None, 'label': None},
                                                                {'term': 'خرید زیست شناسی نشر الگو پایه یازدهم',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'خرید کتاب زیست شناسی', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'خرید کتاب زیست شناسی نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'خرید کتاب زیست نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'خرید کتاب های نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'زیست شناسی نشر الگو', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'زیست شناسی نشر الگو پایه دهم',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'زیست شناسی نشر الگو پایه دوازدهم',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'زیست شناسی نشر الگو پایه یازدهم',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'کتاب جمع بندی زیست شناسی نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'کتاب زیست دوازدهم نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'کتاب زیست شناسی نشر الگو',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'کتاب زیست نشر الگو', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'کنکور', 'scheme': None,
                                                                 'label': None}],
                                                       'id': 'https://www.tahghighestan.ir/?p=37792',
                                                       'guidislink': False,
                                                       'summary': 'کتاب زیست شناسی نشر الگو اشکان هاشمی یکی از مولفین و مدرسین قدیمی با همکاری نشر الگو سری کتاب های زیست نسل جدید را به چاپ رسانیده است. این کتاب های برای مقطع دهم، یازدهم و دوازدهم و همچنین جمع بندی این مقطع به تولید رسیده است. آموزش کامل و مفهومی مفاهیم کتاب درسی در [&#8230;]',
                                                       'summary_detail': {'type': 'text/html', 'language': None,
                                                                          'base': 'https://www.tahghighestan.ir/feed/',
                                                                          'value': 'کتاب زیست شناسی نشر الگو اشکان هاشمی یکی از مولفین و مدرسین قدیمی با همکاری نشر الگو سری کتاب های زیست نسل جدید را به چاپ رسانیده است. این کتاب های برای مقطع دهم، یازدهم و دوازدهم و همچنین جمع بندی این مقطع به تولید رسیده است. آموزش کامل و مفهومی مفاهیم کتاب درسی در [&#8230;]'},
                                                       'wfw_commentrss': 'https://www.tahghighestan.ir/biology-book-publishing-template/feed/',
                                                       'slash_comments': '0'},
    {'title': 'معرفی زبان برنامه نویسی پایتون و نحوه یادگیری آن',
     'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                      'value': 'معرفی زبان برنامه نویسی پایتون و نحوه یادگیری آن'}, 'links': [
        {'rel': 'alternate', 'type': 'text/html',
         'href': 'https://www.tahghighestan.ir/introducing-the-python-programming-language-and-how-to-learn-it/'}],
     'link': 'https://www.tahghighestan.ir/introducing-the-python-programming-language-and-how-to-learn-it/',
     'comments': 'https://www.tahghighestan.ir/introducing-the-python-programming-language-and-how-to-learn-it/#respond',
     'authors': [{'name': 'حسین شریفی'}], 'author': 'حسین شریفی', 'author_detail': {'name': 'حسین شریفی'},
     'published': 'Fri, 13 Aug 2021 22:56:07 +0000',
     'tags': [{'term': 'تکنولوژی و فناوری\u200c', 'scheme': None, 'label': None},
              {'term': 'آموزش برنامه نویسی پایتون', 'scheme': None, 'label': None},
              {'term': 'انواع فریمورک های پایتون', 'scheme': None, 'label': None},
              {'term': 'بازار کار پایتون', 'scheme': None, 'label': None},
              {'term': 'بهترین فریمورک وب پایتون', 'scheme': None, 'label': None},
              {'term': 'بهترین فریمورک پایتون', 'scheme': None, 'label': None},
              {'term': 'تنوع و انعطاف\u200cپذیری پایتون', 'scheme': None, 'label': None},
              {'term': 'زبان برنامه نویسی پایتون', 'scheme': None, 'label': None},
              {'term': 'محبوبیت پایتون', 'scheme': None, 'label': None},
              {'term': 'معرفی زبان برنامه نویسی پایتون', 'scheme': None, 'label': None},
              {'term': 'ویژگی مهم زبان برنامه نویسی پایتون', 'scheme': None, 'label': None},
              {'term': 'پایتون برای چه کسانی مناسب است؟', 'scheme': None, 'label': None},
              {'term': 'پایتون چیست', 'scheme': None, 'label': None},
              {'term': 'کابردهای زبان برنامه نویسی پایتون', 'scheme': None, 'label': None},
              {'term': 'یادگیری پایتون در کوتاه\u200cترین زمان', 'scheme': None, 'label': None}],
     'id': 'https://www.tahghighestan.ir/?p=37715', 'guidislink': False,
     'summary': 'معرفی زبان برنامه نویسی پایتون و نحوه یادگیری آن پایتون از جمله زبان\u200cهای برنامه\u200cنویسی قدرتمندی است که در زمینه علم داده\u200cها، یادگیری ماشینی، خودکارسازی سامانه\u200cها، توسعه وب، واسط\u200cهای برنامه\u200cنویسی و &#8230; به کار گرفته می\u200cشود. در همین راستا مجموعه آموزشی فرادرس که بزرگترین مجموعه آموزش آنلاین کشور می باشد در جهت تولید محتوای آموزشی برنامه [&#8230;]',
     'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                        'value': 'معرفی زبان برنامه نویسی پایتون و نحوه یادگیری آن پایتون از جمله زبان\u200cهای برنامه\u200cنویسی قدرتمندی است که در زمینه علم داده\u200cها، یادگیری ماشینی، خودکارسازی سامانه\u200cها، توسعه وب، واسط\u200cهای برنامه\u200cنویسی و &#8230; به کار گرفته می\u200cشود. در همین راستا مجموعه آموزشی فرادرس که بزرگترین مجموعه آموزش آنلاین کشور می باشد در جهت تولید محتوای آموزشی برنامه [&#8230;]'},
     'wfw_commentrss': 'https://www.tahghighestan.ir/introducing-the-python-programming-language-and-how-to-learn-it/feed/',
     'slash_comments': '0'}, {'title': 'معرفی حافظه داخلی یا Internal در اندروید با مثال',
                              'title_detail': {'type': 'text/plain', 'language': None,
                                               'base': 'https://www.tahghighestan.ir/feed/',
                                               'value': 'معرفی حافظه داخلی یا Internal در اندروید با مثال'},
                              'links': [{'rel': 'alternate', 'type': 'text/html',
                                         'href': 'https://www.tahghighestan.ir/introducing-internal-memory-in-android-with-an-example/'}],
                              'link': 'https://www.tahghighestan.ir/introducing-internal-memory-in-android-with-an-example/',
                              'comments': 'https://www.tahghighestan.ir/introducing-internal-memory-in-android-with-an-example/#respond',
                              'authors': [{'name': 'حسین شریفی'}], 'author': 'حسین شریفی',
                              'author_detail': {'name': 'حسین شریفی'},
                              'published': 'Fri, 06 Aug 2021 13:47:23 +0000',
                              'tags': [{'term': 'تکنولوژی و فناوری\u200c', 'scheme': None, 'label': None},
                                       {'term': 'آموزش برنامه نویسی اندروید', 'scheme': None, 'label': None},
                                       {'term': 'اندروید', 'scheme': None, 'label': None},
                                       {'term': 'حافظه اینترنال اندروید', 'scheme': None, 'label': None},
                                       {'term': 'حافظه داخلی اندروید', 'scheme': None, 'label': None},
                                       {'term': 'معرفی حافظه داخلی اندروید', 'scheme': None, 'label': None},
                                       {'term': 'معرفی حافظه داخلی یا Internal', 'scheme': None, 'label': None},
                                       {'term': 'معرفی حافظه داخلی یا Internal در اندروید با مثال',
                                        'scheme': None, 'label': None}],
                              'id': 'https://www.tahghighestan.ir/?p=37560', 'guidislink': False,
                              'summary': 'معرفی حافظه داخلی یا Internal در اندروید با مثال اندروید حافظه های متفاوتی برای ذخیره سازی داده های مربوط به اپلیکیشن ها ارائه می دهد. این حافظه ها عبارتند از: preference های به اشتراک گذاشته شده حافظه ی داخلی (internal) حافظه ی خارجی (external storage) حافظه ی QLite ذخیره سازی از طریق اتصال به شبکه [&#8230;]',
                              'summary_detail': {'type': 'text/html', 'language': None,
                                                 'base': 'https://www.tahghighestan.ir/feed/',
                                                 'value': 'معرفی حافظه داخلی یا Internal در اندروید با مثال اندروید حافظه های متفاوتی برای ذخیره سازی داده های مربوط به اپلیکیشن ها ارائه می دهد. این حافظه ها عبارتند از: preference های به اشتراک گذاشته شده حافظه ی داخلی (internal) حافظه ی خارجی (external storage) حافظه ی QLite ذخیره سازی از طریق اتصال به شبکه [&#8230;]'},
                              'wfw_commentrss': 'https://www.tahghighestan.ir/introducing-internal-memory-in-android-with-an-example/feed/',
                              'slash_comments': '0'}, {'title': 'صفحه 603 قران (سوره کافرون) – استخاره با قران',
                                                       'title_detail': {'type': 'text/plain', 'language': None,
                                                                        'base': 'https://www.tahghighestan.ir/feed/',
                                                                        'value': 'صفحه 603 قران (سوره کافرون) – استخاره با قران'},
                                                       'links': [{'rel': 'alternate', 'type': 'text/html',
                                                                  'href': 'https://www.tahghighestan.ir/quran-603/'},
                                                                 {'length': '449434', 'type': 'audio/mpeg',
                                                                  'href': 'https://www.tahghighestan.ir/wp-content/uploads/2021/07/quran-603.mp3',
                                                                  'rel': 'enclosure'}],
                                                       'link': 'https://www.tahghighestan.ir/quran-603/',
                                                       'comments': 'https://www.tahghighestan.ir/quran-603/#respond',
                                                       'authors': [{'name': 'zahrasaniei1377'}],
                                                       'author': 'zahrasaniei1377',
                                                       'author_detail': {'name': 'zahrasaniei1377'},
                                                       'published': 'Fri, 23 Jul 2021 05:30:34 +0000',
                                                       'tags': [{'term': 'استخاره با قران', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'سرگرمی', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'آیات صفحه 603 قران', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'استخاره صفحه 603 قران',
                                                                 'scheme': None, 'label': None},
                                                                {'term': 'تفسیر صفحه 603 قران', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'تلاوت سوره عصر با صدای سعد الغامدی',
                                                                 'scheme': None, 'label': None}, {
                                                                    'term': 'تلاوت صفحه 603 قران با صدای سعد الغامدی',
                                                                    'scheme': None, 'label': None},
                                                                {'term': 'سوره عصر', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'صفحه 603 قران', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'صوت سوره عصر', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'معنی صفحه 603 قران', 'scheme': None,
                                                                 'label': None},
                                                                {'term': 'نتیجه استخاره صفحه 603 قران',
                                                                 'scheme': None, 'label': None}],
                                                       'id': 'https://www.tahghighestan.ir/?p=37555',
                                                       'guidislink': False,
                                                       'summary': 'صفحه 603 قران\xa0(سوره کافرون) &#8211; استخاره با قران صفحه 603 قران در برگیرنده سوره کافرون است. این سوره صد ونهمین سوره قران می\u200cباشد و دارای 6 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 603 قران را در تحقیقستان بخوانید. صفحه 603 قران (سوره کافرون) &#8211; معنی صفحه 603 [&#8230;]',
                                                       'summary_detail': {'type': 'text/html', 'language': None,
                                                                          'base': 'https://www.tahghighestan.ir/feed/',
                                                                          'value': 'صفحه 603 قران\xa0(سوره کافرون) &#8211; استخاره با قران صفحه 603 قران در برگیرنده سوره کافرون است. این سوره صد ونهمین سوره قران می\u200cباشد و دارای 6 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 603 قران را در تحقیقستان بخوانید. صفحه 603 قران (سوره کافرون) &#8211; معنی صفحه 603 [&#8230;]'},
                                                       'wfw_commentrss': 'https://www.tahghighestan.ir/quran-603/feed/',
                                                       'slash_comments': '0'},
    {'title': 'صفحه 601 قران (سوره عصر) – استخاره با قران',
     'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                      'value': 'صفحه 601 قران (سوره عصر) – استخاره با قران'},
     'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.tahghighestan.ir/quran-601/'},
               {'length': '453744', 'type': 'audio/mpeg',
                'href': 'https://www.tahghighestan.ir/wp-content/uploads/2021/07/quran-601.mp3',
                'rel': 'enclosure'}], 'link': 'https://www.tahghighestan.ir/quran-601/',
     'comments': 'https://www.tahghighestan.ir/quran-601/#respond', 'authors': [{'name': 'zahrasaniei1377'}],
     'author': 'zahrasaniei1377', 'author_detail': {'name': 'zahrasaniei1377'},
     'published': 'Fri, 23 Jul 2021 05:30:10 +0000',
     'tags': [{'term': 'استخاره با قران', 'scheme': None, 'label': None},
              {'term': 'سرگرمی', 'scheme': None, 'label': None},
              {'term': 'آیات صفحه 601 قران', 'scheme': None, 'label': None},
              {'term': 'استخاره صفحه 601 قران', 'scheme': None, 'label': None},
              {'term': 'تفسیر صفحه 601 قران', 'scheme': None, 'label': None},
              {'term': 'تلاوت سوره عصر با صدای سعد الغامدی', 'scheme': None, 'label': None},
              {'term': 'تلاوت صفحه 601 قران با صدای سعد الغامدی', 'scheme': None, 'label': None},
              {'term': 'سوره عصر', 'scheme': None, 'label': None},
              {'term': 'صفحه 601 قران', 'scheme': None, 'label': None},
              {'term': 'صوت سوره عصر', 'scheme': None, 'label': None},
              {'term': 'معنی صفحه 601 قران', 'scheme': None, 'label': None},
              {'term': 'نتیجه استخاره صفحه 601 قران', 'scheme': None, 'label': None}],
     'id': 'https://www.tahghighestan.ir/?p=37553', 'guidislink': False,
     'summary': 'صفحه 601 قران\xa0(سوره عصر) &#8211; استخاره با قران صفحه 601 قران در برگیرنده سوره عصر است. این سوره صد وسومین سوره قران می\u200cباشد و دارای 3 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 601 قران را در تحقیقستان بخوانید. صفحه 601 قران (سوره عصر) &#8211; معنی صفحه 601 [&#8230;]',
     'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                        'value': 'صفحه 601 قران\xa0(سوره عصر) &#8211; استخاره با قران صفحه 601 قران در برگیرنده سوره عصر است. این سوره صد وسومین سوره قران می\u200cباشد و دارای 3 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 601 قران را در تحقیقستان بخوانید. صفحه 601 قران (سوره عصر) &#8211; معنی صفحه 601 [&#8230;]'},
     'wfw_commentrss': 'https://www.tahghighestan.ir/quran-601/feed/', 'slash_comments': '0'},
    {'title': 'صفحه 595 قران (سوره شمس) – استخاره با قران',
     'title_detail': {'type': 'text/plain', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                      'value': 'صفحه 595 قران (سوره شمس) – استخاره با قران'},
     'links': [{'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.tahghighestan.ir/quran-595/'},
               {'length': '631116', 'type': 'audio/mpeg',
                'href': 'https://www.tahghighestan.ir/wp-content/uploads/2021/07/quran-595.mp3',
                'rel': 'enclosure'}], 'link': 'https://www.tahghighestan.ir/quran-595/',
     'comments': 'https://www.tahghighestan.ir/quran-595/#respond', 'authors': [{'name': 'zahrasaniei1377'}],
     'author': 'zahrasaniei1377', 'author_detail': {'name': 'zahrasaniei1377'},
     'published': 'Thu, 22 Jul 2021 05:30:50 +0000',
     'tags': [{'term': 'استخاره با قران', 'scheme': None, 'label': None},
              {'term': 'سرگرمی', 'scheme': None, 'label': None},
              {'term': 'آیات صفحه 595 قران', 'scheme': None, 'label': None},
              {'term': 'استخاره صفحه 595 قران', 'scheme': None, 'label': None},
              {'term': 'تفسیر صفحه 595 قران', 'scheme': None, 'label': None},
              {'term': 'تلاوت سوره شمس با صدای سعد الغامدی', 'scheme': None, 'label': None},
              {'term': 'تلاوت صفحه 595 قران با صدای سعد الغامدی', 'scheme': None, 'label': None},
              {'term': 'سوره شمس', 'scheme': None, 'label': None},
              {'term': 'صفحه 595 قران', 'scheme': None, 'label': None},
              {'term': 'صوت سوره شمس', 'scheme': None, 'label': None},
              {'term': 'معنی صفحه 595 قران', 'scheme': None, 'label': None},
              {'term': 'نتیجه استخاره صفحه 595 قران', 'scheme': None, 'label': None}],
     'id': 'https://www.tahghighestan.ir/?p=37546', 'guidislink': False,
     'summary': 'صفحه 595 قران\xa0(سوره شمس) &#8211; استخاره با قران صفحه 595 قران در برگیرنده سوره شمس است. این سوره نود ویکمین سوره قران می\u200cباشد و دارای 15 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 595 قران را در تحقیقستان بخوانید. صفحه 595 قران (سوره شمس) &#8211; معنی صفحه 595 [&#8230;]',
     'summary_detail': {'type': 'text/html', 'language': None, 'base': 'https://www.tahghighestan.ir/feed/',
                        'value': 'صفحه 595 قران\xa0(سوره شمس) &#8211; استخاره با قران صفحه 595 قران در برگیرنده سوره شمس است. این سوره نود ویکمین سوره قران می\u200cباشد و دارای 15 آیه شریفه است. استخاره با قران با معنی و تعبیر کامل و تفسیر صفحه 595 قران را در تحقیقستان بخوانید. صفحه 595 قران (سوره شمس) &#8211; معنی صفحه 595 [&#8230;]'},
     'wfw_commentrss': 'https://www.tahghighestan.ir/quran-595/feed/', 'slash_comments': '0'}],
               'feed': {'title': 'تحقیقستان', 'title_detail': {'type': 'text/plain', 'language': None,
                                                               'base': 'https://www.tahghighestan.ir/feed/',
                                                               'value': 'تحقیقستان'}, 'links': [
                   {'href': 'https://www.tahghighestan.ir/feed/', 'rel': 'self',
                    'type': 'application/rss+xml'},
                   {'rel': 'alternate', 'type': 'text/html', 'href': 'https://www.tahghighestan.ir'}],
                        'link': 'https://www.tahghighestan.ir', 'subtitle': 'مرجع مقالات و محصولات آموزشی',
                        'subtitle_detail': {'type': 'text/html', 'language': None,
                                            'base': 'https://www.tahghighestan.ir/feed/',
                                            'value': 'مرجع مقالات و محصولات آموزشی'},
                        'updated': 'Mon, 27 Dec 2021 10:20:05 +0000', 'language': 'fa-IR',
                        'sy_updateperiod': 'hourly', 'sy_updatefrequency': '1',
                        'generator_detail': {'name': 'https://wordpress.org/?v=5.8.2'},
                        'generator': 'https://wordpress.org/?v=5.8.2', 'image': {
                       'href': 'https://www.tahghighestan.ir/wp-content/uploads/2020/08/cropped-icon-70x70.png',
                       'title': 'تحقیقستان', 'title_detail': {'type': 'text/plain', 'language': None,
                                                              'base': 'https://www.tahghighestan.ir/feed/',
                                                              'value': 'تحقیقستان'}, 'links': [
                           {'rel': 'alternate', 'type': 'text/html',
                            'href': 'https://www.tahghighestan.ir'}],
                       'link': 'https://www.tahghighestan.ir', 'width': 32, 'height': 32}},
               'headers': {'date': 'Sat, 01 Jan 2022 18:43:22 GMT',
                           'content-type': 'application/rss+xml; charset=UTF-8',
                           'transfer-encoding': 'chunked', 'connection': 'close',
                           'cf-edge-cache': 'cache,platform=wordpress',
                           'last-modified': 'Wed, 29 Dec 2021 14:38:01 GMT',
                           'link': '<https://www.tahghighestan.ir/wp-json/>; rel="https://api.w.org/"',
                           'vary': 'Accept-Encoding,User-Agent,User-Agent,Accept-Encoding',
                           'cache-control': 'public, max-age=3600',
                           'expires': 'Sat, 01 Jan 2022 19:43:22 GMT', 'content-encoding': 'gzip',
                           'x-turbo-charged-by': 'LiteSpeed', 'cf-cache-status': 'DYNAMIC',
                           'expect-ct': 'max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"',
                           'report-to': '{"endpoints":[{"url":"https:\\/\\/a.nel.cloudflare.com\\/report\\/v3?s=6ClTAq%2BUh5u3O8s022LjccLQ%2F5cVoF5l2GZpGV9oRV%2FfB7V65%2FbuzjhrrPrJA8JbWIc0nopBzpUzOD092%2BGFA3H6M16GfgehkpncnZQWN9OlpJGQT7e7d0j8P9ThAFuAgiZRaC85kUPRO9IAeWdiedm4Eg%3D%3D"}],"group":"cf-nel","max_age":604800}',
                           'nel': '{"success_fraction":0,"report_to":"cf-nel","max_age":604800}',
                           'server': 'cloudflare', 'cf-ray': '6c6de48cecee68f7-FRA',
                           'alt-svc': 'h3=":443"; ma=86400, h3-29=":443"; ma=86400, h3-28=":443"; ma=86400, h3-27=":443"; ma=86400'},
               'updated': 'Wed, 29 Dec 2021 14:38:01 GMT',
               'href': 'https://www.tahghighestan.ir/feed/', 'status': 200, 'encoding': 'UTF-8',
               'version': 'rss20', 'namespaces': {'content': 'http://purl.org/rss/1.0/modules/content/',
                                                  'wfw': 'http://wellformedweb.org/CommentAPI/',
                                                  'dc': 'http://purl.org/dc/elements/1.1/',
                                                  '': 'http://www.w3.org/2005/Atom',
                                                  'sy': 'http://purl.org/rss/1.0/modules/syndication/',
                                                  'slash': 'http://purl.org/rss/1.0/modules/slash/'}}
