# Generated by Django 3.2.10 on 2022-01-02 17:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RSSFeed',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Active?')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Creation Time')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Update Time')),
                ('removed', models.DateTimeField(blank=True, null=True, verbose_name='Remove Time')),
                ('url', models.URLField(db_index=True)),
                ('feed_version', models.PositiveSmallIntegerField(choices=[(0, 'rss20'), (1, 'atom10')])),
                ('category', models.PositiveSmallIntegerField(blank=True, choices=[(0, 'tech'), (1, 'programming'), (2, 'economy'), (4, 'business'), (5, 'science'), (6, 'culture')], null=True)),
                ('last_try', models.DateTimeField(null=True)),
                ('name', models.CharField(max_length=500)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FeedItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=500, null=True)),
                ('date', models.DateTimeField(blank=True, max_length=500, null=True)),
                ('link', models.URLField(blank=True, max_length=500, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('author', models.CharField(blank=True, max_length=500, null=True)),
                ('rss_feed', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='fetcher.rssfeed')),
            ],
        ),
    ]
